### ISSUE TITLE
None registered Notification Handler MUST throw an exception

### ISSUE THREAD

**Issue by TacB0sS** [nu-art/cyborg-core#5]
When asking for a none registered Notification handler, throw a BadImplementationException with detailed explanation!

**Comment by TacB0sS** [comment]
Consider to remove the need to add a notification handler and create a new "get or create"notification handler method, that would initialize the handlers lazily..? @hedshafran?

**Comment by hedshafran** [comment]
@TacB0sS The getOrCreateNotificationHandler sounds good.
I think the name should be getNotificationHandler, it's shorter and any way you only want the handler, not to know if it was just created or not..

**Comment by TacB0sS** [comment]
Implemented
