### ISSUE TITLE
Resolve this stupid: NOT PUSHING NEW LAYER... TRANSITION ANIMATION IN PROGRESS!!!

### ISSUE THREAD

**Issue by TacB0sS** [nu-art/cyborg-core#7]
Two scenarios.. 
1. a short timed splash screen that will try to display another screen before its own animation ends (I know a lame example, but still an example)
2. stack of screen with a meaningful animation between (Views flying around between the screens, Shared Element) and user presses back too quickly.

What is the expected behaviour.

**Comment by TacB0sS** [comment]
@hedshafran what do you think is the proper action when while one controller animates in (or out), another tries to animate it self same as the previous one... like in the case a user press back 20 times a sec?

**Comment by hedshafran** [comment]
@TacB0sS First of all, cases like this that are related to user operations should be prevented using the 'canExecute' thing..
In general I think that transition animations (specifically) should respect one another and wait for the current animation to complete. So when a new controller tries to start the transition, the transition should be run using a delayed handler, so theoretically you can have a stack of pending transitions executing one after another.
This should be relevant only for controller transition animations in the same StackLayer! If it's a different stack the new animation should start immediately.

**Comment by TacB0sS** [comment]
@hedshafran 

You know me... I take it all to the extreme.. so:

Assuming the navigation involves 10 layers, with a ridicules animation of 1 sec between a layer... the user will have to wait 10 sec before leaving the app! 

So as much as I would like this **clean** solution..  I guess it is a _miss_ from the UX perspective...

**Comment by TacB0sS** [comment]
removed the condition early exiting the push and pop while another transition is in progress
